import { makeStyles, tokens } from '@fluentui/react-components';

export const useExplorerStyles = makeStyles({
    page: {
        display: 'flex',
        flexDirection: 'column',
        height: 'calc(100vh - 57px)',
        margin: '-24px',
        overflow: 'hidden',
    },
    pageWebView: {
        display: 'flex',
        flexDirection: 'column',
        height: 'calc(100vh - 1px)',
        margin: '-24px',
        overflow: 'hidden',
    },
    queryTabBar: {
        display: 'flex',
        alignItems: 'center',
        backgroundColor: tokens.colorNeutralBackground1,
        borderBottom: `1px solid ${tokens.colorNeutralStroke2}`,
        minHeight: '36px',
        overflow: 'hidden',
    },
    queryTabList: {
        display: 'flex',
        alignItems: 'center',
        flex: 1,
        overflow: 'auto',
        gap: '0',
    },
    queryTab: {
        display: 'flex',
        alignItems: 'center',
        gap: '6px',
        padding: '6px 12px',
        fontSize: '12px',
        cursor: 'pointer',
        color: tokens.colorNeutralForeground3,
        borderRight: `1px solid ${tokens.colorNeutralStroke2}`,
        whiteSpace: 'nowrap' as const,
        userSelect: 'none' as const,
        '&:hover': {
            backgroundColor: tokens.colorNeutralBackground2,
            color: tokens.colorNeutralForeground1,
        },
    },
    queryTabActive: {
        display: 'flex',
        alignItems: 'center',
        gap: '6px',
        padding: '6px 12px',
        fontSize: '12px',
        cursor: 'pointer',
        color: tokens.colorNeutralForeground1,
        backgroundColor: tokens.colorNeutralBackground2,
        borderRight: `1px solid ${tokens.colorNeutralStroke2}`,
        borderBottom: `2px solid ${tokens.colorBrandForeground1}`,
        whiteSpace: 'nowrap' as const,
        userSelect: 'none' as const,
    },
    queryTabClose: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        width: '16px',
        height: '16px',
        padding: '0',
        cursor: 'pointer',
        color: tokens.colorNeutralForeground3,
        borderRadius: '3px',
        '&:hover': {
            color: tokens.colorNeutralForeground1,
            backgroundColor: tokens.colorNeutralBackground3,
        },
    },
    contextMenu: {
        position: 'absolute' as const,
        zIndex: 100,
        backgroundColor: tokens.colorNeutralBackground1,
        border: `1px solid ${tokens.colorNeutralStroke1}`,
        borderRadius: '4px',
        boxShadow: '0 4px 12px rgba(0, 0, 0, 0.15)',
        padding: '4px 0',
        minWidth: '120px',
    },
    contextMenuItem: {
        padding: '6px 12px',
        fontSize: '12px',
        cursor: 'pointer',
        color: tokens.colorNeutralForeground1,
        '&:hover': {
            backgroundColor: tokens.colorNeutralBackground2,
        },
    },
    contextMenuDanger: {
        padding: '6px 12px',
        fontSize: '12px',
        cursor: 'pointer',
        color: tokens.colorPaletteRedForeground1,
        '&:hover': {
            backgroundColor: tokens.colorPaletteRedBackground1,
        },
    },
    editorDropTarget: {
        position: 'absolute' as const,
        backgroundColor: 'rgba(0, 120, 212, 0.1)',
        border: `2px dashed ${tokens.colorBrandStroke1}`,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 10,
        pointerEvents: 'none' as const,
        fontSize: '12px',
        color: tokens.colorBrandForeground1,
        fontWeight: '600',
    },
    queryTabActions: {
        display: 'flex',
        alignItems: 'center',
        gap: '2px',
        padding: '0 4px',
    },
    activeFilter: {
        color: tokens.colorBrandForeground1,
    },
    toolbar: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: '4px 12px',
        backgroundColor: tokens.colorNeutralBackground2,
        borderBottom: `1px solid ${tokens.colorNeutralStroke2}`,
        minHeight: '36px',
    },
    toolbarLeft: {
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
    },
    toolbarRight: {
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
    },
    splitContainer: {
        display: 'flex',
        flexDirection: 'column',
        flex: 1,
        minHeight: 0,
        overflow: 'hidden',
    },
    editorArea: {
        display: 'flex',
        flexDirection: 'row',
        minHeight: 0,
        overflow: 'hidden',
    },
    schemaList: {
        width: '100%',
        height: '100%',
        borderRight: `1px solid ${tokens.colorNeutralStroke2}`,
        backgroundColor: tokens.colorNeutralBackground2,
        overflow: 'hidden',
        padding: '0',
        fontSize: '12px',
        display: 'flex',
        flexDirection: 'column',
    },
    schemaSearch: {
        padding: '4px 6px',
        borderBottom: `1px solid ${tokens.colorNeutralStroke2}`,
        flexShrink: 0,
    },
    schemaSearchInput: {
        width: '100%',
        fontSize: '11px',
    },
    schemaResizeHandle: {
        width: '4px',
        cursor: 'col-resize',
        backgroundColor: 'transparent',
        flexShrink: 0,
        '&:hover': {
            backgroundColor: tokens.colorBrandBackground,
        },
    },
    schemaTree: {
        flex: 1,
        overflow: 'auto',
        padding: '2px 0',
    },
    folderRow: {
        display: 'flex',
        alignItems: 'center',
        gap: '4px',
        padding: '4px 8px',
        cursor: 'pointer',
        color: tokens.colorNeutralForeground3,
        fontWeight: '600',
        fontSize: '11px',
        userSelect: 'none' as const,
        whiteSpace: 'nowrap' as const,
        overflow: 'hidden',
        '&:hover': {
            backgroundColor: tokens.colorNeutralBackground3,
        },
    },
    schemaItem: {
        display: 'flex',
        alignItems: 'center',
        gap: '4px',
        padding: '3px 8px 3px 20px',
        cursor: 'pointer',
        color: tokens.colorNeutralForeground2,
        whiteSpace: 'nowrap' as const,
        overflow: 'hidden',
        textOverflow: 'ellipsis',
        fontSize: '11px',
        '&:hover': {
            backgroundColor: tokens.colorNeutralBackground3,
            color: tokens.colorNeutralForeground1,
        },
    },
    schemaColumn: {
        display: 'flex',
        alignItems: 'center',
        gap: '4px',
        padding: '2px 8px 2px 40px',
        cursor: 'pointer',
        color: tokens.colorNeutralForeground3,
        whiteSpace: 'nowrap' as const,
        overflow: 'hidden',
        textOverflow: 'ellipsis',
        fontSize: '10px',
        '&:hover': {
            backgroundColor: tokens.colorNeutralBackground3,
            color: tokens.colorNeutralForeground2,
        },
    },
    schemaColType: {
        color: tokens.colorNeutralForeground4,
        fontSize: '9px',
        marginLeft: 'auto',
        flexShrink: 0,
    },
    editorContainer: {
        flex: 1,
        minWidth: 0,
        minHeight: 0,
        position: 'relative' as const,
    },
    editorSplitHandle: {
        backgroundColor: tokens.colorNeutralStroke1,
        flexShrink: 0,
        '&:hover': {
            backgroundColor: tokens.colorBrandBackground,
        },
    },
    editorSplitArea: {
        display: 'flex',
        flex: 1,
        minWidth: 0,
        minHeight: 0,
        overflow: 'hidden',
    },
    editorPaneFocused: {
        flex: 1,
        minWidth: 0,
        minHeight: 0,
        outline: `1px solid ${tokens.colorBrandStroke1}`,
        outlineOffset: '-1px',
    },
    editorPaneUnfocused: {
        flex: 1,
        minWidth: 0,
        minHeight: 0,
    },
    dragHandle: {
        height: '4px',
        cursor: 'row-resize',
        backgroundColor: tokens.colorNeutralStroke1,
        flexShrink: 0,
        '&:hover': {
            height: '6px',
            backgroundColor: tokens.colorBrandBackground,
        },
    },
    resultsPanel: {
        minHeight: '80px',
        display: 'flex',
        flexDirection: 'column',
        overflow: 'hidden',
    },
    resultsHeader: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: '4px 12px',
        backgroundColor: tokens.colorNeutralBackground2,
        borderBottom: `1px solid ${tokens.colorNeutralStroke2}`,
        minHeight: '32px',
    },
    resultsStats: {
        display: 'flex',
        gap: '12px',
        alignItems: 'center',
    },
    stat: {
        color: tokens.colorNeutralForeground3,
        fontSize: '11px',
    },
    errorBox: {
        margin: '8px',
        padding: '8px 12px',
        borderRadius: '4px',
        backgroundColor: tokens.colorPaletteRedBackground1,
        color: tokens.colorPaletteRedForeground1,
        fontFamily: 'Consolas, Monaco, monospace',
        fontSize: '12px',
        whiteSpace: 'pre-wrap' as const,
    },
    emptyState: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        gap: '8px',
        flex: 1,
        color: tokens.colorNeutralForeground3,
    },
    tabStrip: {
        display: 'flex',
        alignItems: 'center',
        gap: '0',
    },
    tab: {
        padding: '4px 12px',
        fontSize: '11px',
        fontWeight: '600',
        cursor: 'pointer',
        color: tokens.colorNeutralForeground3,
        userSelect: 'none' as const,
        backgroundColor: 'transparent',
        borderTop: 'none',
        borderLeft: 'none',
        borderRight: 'none',
        borderBottom: '2px solid transparent',
        outline: 'none',
        '&:hover': {
            color: tokens.colorNeutralForeground1,
        },
    },
    tabActive: {
        padding: '4px 12px',
        fontSize: '11px',
        fontWeight: '600',
        cursor: 'pointer',
        color: tokens.colorBrandForeground1,
        userSelect: 'none' as const,
        backgroundColor: 'transparent',
        borderTop: 'none',
        borderLeft: 'none',
        borderRight: 'none',
        borderBottom: `2px solid ${tokens.colorBrandForeground1}`,
        outline: 'none',
    },
    historyList: {
        flex: 1,
        overflow: 'auto',
        padding: '0',
    },
    historyItem: {
        display: 'flex',
        flexDirection: 'column',
        gap: '2px',
        padding: '8px 12px',
        cursor: 'pointer',
        backgroundColor: 'transparent',
        borderTop: 'none',
        borderLeft: 'none',
        borderRight: 'none',
        borderBottom: `1px solid ${tokens.colorNeutralStroke2}`,
        outline: 'none',
        textAlign: 'left' as const,
        width: '100%',
        '&:hover': {
            backgroundColor: tokens.colorNeutralBackground2,
        },
    },
    historyQuery: {
        fontFamily: 'Consolas, Monaco, monospace',
        fontSize: '11px',
        color: tokens.colorNeutralForeground1,
        whiteSpace: 'nowrap' as const,
        overflow: 'hidden',
        textOverflow: 'ellipsis',
    },
    historyMeta: {
        display: 'flex',
        gap: '12px',
        fontSize: '10px',
        color: tokens.colorNeutralForeground3,
    },
    historyError: {
        color: tokens.colorPaletteRedForeground1,
    },
    historyRecallable: {
        color: tokens.colorBrandForeground1,
        fontSize: '10px',
    },
    statsGrid: {
        display: 'grid',
        gridTemplateColumns: '1fr 1fr',
        gap: '0',
        flex: 1,
        overflow: 'auto',
        alignContent: 'start',
    },
    statsCard: {
        display: 'flex',
        flexDirection: 'column',
        gap: '2px',
        padding: '10px 16px',
        borderBottom: `1px solid ${tokens.colorNeutralStroke2}`,
        borderRight: `1px solid ${tokens.colorNeutralStroke2}`,
    },
    statsLabel: {
        fontSize: '10px',
        color: tokens.colorNeutralForeground3,
        textTransform: 'uppercase' as const,
        letterSpacing: '0.5px',
    },
    statsValue: {
        fontSize: '14px',
        fontFamily: 'Consolas, Monaco, monospace',
        color: tokens.colorNeutralForeground1,
    },
});
