import { makeStyles, tokens } from '@fluentui/react-components';

const EXPAND_COL_WIDTH = 24;

export const useStyles = makeStyles({
    container: { display: 'flex', flexDirection: 'column', flex: 1, minHeight: 0, overflow: 'hidden' },
    toolbar: { display: 'flex', alignItems: 'center', gap: '6px', padding: '4px 8px', borderBottom: `1px solid ${tokens.colorNeutralStroke2}`, backgroundColor: tokens.colorNeutralBackground2, flexShrink: 0 },
    searchInput: { maxWidth: '280px', fontSize: '11px' },
    highlightInput: { maxWidth: '250px', fontSize: '11px' },
    bodyArea: { display: 'flex', flex: 1, minHeight: 0, overflow: 'hidden' },
    scrollContainer: { flex: 1, minHeight: 0 },
    thead: { position: 'sticky' as const, top: 0, zIndex: 2 },
    thRow: { display: 'flex' },
    th: {
        display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '4px 8px',
        backgroundColor: tokens.colorNeutralBackground3, borderBottom: `1px solid ${tokens.colorNeutralStroke1}`,
        borderRight: `1px solid ${tokens.colorNeutralStroke2}`, borderTop: 'none', borderLeft: 'none',
        color: tokens.colorNeutralForeground2, outline: 'none',
        fontWeight: '600', fontSize: '11px', cursor: 'pointer', userSelect: 'none' as const,
        whiteSpace: 'nowrap' as const, boxSizing: 'border-box' as const, flexShrink: 0,
        '&:hover': { backgroundColor: tokens.colorNeutralBackground4 },
    },
    thExpand: {
        display: 'flex', alignItems: 'center', justifyContent: 'center',
        width: `${EXPAND_COL_WIDTH}px`, minWidth: `${EXPAND_COL_WIDTH}px`, maxWidth: `${EXPAND_COL_WIDTH}px`,
        padding: '4px 0', backgroundColor: tokens.colorNeutralBackground3,
        borderBottom: `1px solid ${tokens.colorNeutralStroke1}`, borderRight: `1px solid ${tokens.colorNeutralStroke2}`,
        boxSizing: 'border-box' as const, flexShrink: 0,
    },
    thLabel: { display: 'flex', alignItems: 'center', gap: '4px', overflow: 'hidden' },
    thName: { overflow: 'hidden', textOverflow: 'ellipsis' },
    filterRow: { display: 'flex' },
    filterCell: {
        padding: '2px 4px', backgroundColor: tokens.colorNeutralBackground3,
        borderBottom: `1px solid ${tokens.colorNeutralStroke1}`, borderRight: `1px solid ${tokens.colorNeutralStroke2}`,
        boxSizing: 'border-box' as const, flexShrink: 0,
    },
    filterInput: { width: '100%', fontSize: '10px' },
    tr: { display: 'flex', '&:hover': { backgroundColor: tokens.colorNeutralBackground2 } },
    trDetailOpen: { display: 'flex', backgroundColor: 'rgba(0, 120, 212, 0.06)' },
    trExprHighlight: { display: 'flex', backgroundColor: 'rgba(255, 200, 0, 0.12)', '&:hover': { backgroundColor: 'rgba(255, 200, 0, 0.2)' } },
    td: {
        padding: '3px 8px', borderBottom: `1px solid ${tokens.colorNeutralStroke2}`,
        borderRight: `1px solid ${tokens.colorNeutralStroke2}`, color: tokens.colorNeutralForeground1,
        whiteSpace: 'nowrap' as const, overflow: 'hidden', textOverflow: 'ellipsis',
        boxSizing: 'border-box' as const, flexShrink: 0, cursor: 'default',
        userSelect: 'none' as const, fontFamily: 'Consolas, Monaco, monospace', fontSize: '12px',
    },
    tdSelected: {
        padding: '3px 8px', borderBottom: `1px solid ${tokens.colorNeutralStroke2}`,
        borderRight: `1px solid ${tokens.colorNeutralStroke2}`, color: tokens.colorNeutralForeground1,
        whiteSpace: 'nowrap' as const, overflow: 'hidden', textOverflow: 'ellipsis',
        boxSizing: 'border-box' as const, flexShrink: 0, cursor: 'default',
        userSelect: 'none' as const, fontFamily: 'Consolas, Monaco, monospace', fontSize: '12px',
        backgroundColor: 'rgba(0, 120, 212, 0.15)',
    },
    expandBtn: {
        display: 'flex', alignItems: 'center', justifyContent: 'center',
        width: `${EXPAND_COL_WIDTH}px`, minWidth: `${EXPAND_COL_WIDTH}px`, maxWidth: `${EXPAND_COL_WIDTH}px`,
        padding: '0', borderBottom: `1px solid ${tokens.colorNeutralStroke2}`,
        borderRight: `1px solid ${tokens.colorNeutralStroke2}`, boxSizing: 'border-box' as const,
        borderTop: 'none', borderLeft: 'none', backgroundColor: 'transparent', outline: 'none',
        flexShrink: 0, cursor: 'pointer', color: tokens.colorNeutralForeground3,
        '&:hover': { color: tokens.colorBrandForeground1 },
    },
    colPickerList: { display: 'flex', flexDirection: 'column', gap: '2px', maxHeight: '300px', overflow: 'auto', padding: '4px', minWidth: '180px' },
    colPickerActions: { display: 'flex', gap: '4px', padding: '4px 4px 0', borderTop: `1px solid ${tokens.colorNeutralStroke2}`, marginTop: '4px' },
    activeFilter: { color: tokens.colorBrandForeground1 },
    sortIcon: { fontSize: '10px', flexShrink: 0 },
    statusBar: {
        display: 'flex', alignItems: 'center', gap: '12px', padding: '2px 8px',
        borderTop: `1px solid ${tokens.colorNeutralStroke2}`, backgroundColor: tokens.colorNeutralBackground2,
        fontSize: '10px', color: tokens.colorNeutralForeground3, flexShrink: 0, flexWrap: 'wrap' as const,
    },
    statusLeft: { display: 'flex', gap: '12px', alignItems: 'center' },
    statusRight: { display: 'flex', gap: '12px', alignItems: 'center', marginLeft: 'auto' },
    statHighlight: { color: tokens.colorBrandForeground1, fontWeight: '600' },
    detailPanel: {
        display: 'flex', flexDirection: 'column', overflow: 'hidden',
        borderLeft: `1px solid ${tokens.colorNeutralStroke1}`, backgroundColor: tokens.colorNeutralBackground2,
    },
    detailDragHandle: {
        width: '4px', cursor: 'col-resize', backgroundColor: tokens.colorNeutralStroke1, flexShrink: 0,
        '&:hover': { width: '6px', backgroundColor: tokens.colorBrandBackground },
    },
    detailHeader: {
        display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '6px 10px',
        borderBottom: `1px solid ${tokens.colorNeutralStroke2}`, fontWeight: '600', fontSize: '11px',
        color: tokens.colorNeutralForeground2, flexShrink: 0, gap: '4px',
    },
    detailHeaderLeft: { display: 'flex', alignItems: 'center', gap: '4px' },
    detailBody: { flex: 1, overflow: 'auto', padding: '4px 0' },
    detailRow: {
        display: 'flex', padding: '3px 10px', fontSize: '11px', fontFamily: 'Consolas, Monaco, monospace',
        borderBottom: `1px solid ${tokens.colorNeutralStroke2}`, gap: '8px',
        '&:hover': { backgroundColor: tokens.colorNeutralBackground3 },
    },
    detailKey: { width: '140px', minWidth: '140px', flexShrink: 0, color: tokens.colorNeutralForeground3, fontWeight: '600', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' as const, borderRight: `1px solid ${tokens.colorNeutralStroke2}`, paddingRight: '8px' },
    detailValue: { flex: 1, color: tokens.colorNeutralForeground1, wordBreak: 'break-all' as const, whiteSpace: 'pre-wrap' as const, minWidth: 0 },
    detailListRow: {
        display: 'flex', flexDirection: 'column', padding: '4px 10px', fontSize: '11px', fontFamily: 'Consolas, Monaco, monospace',
        borderBottom: `1px solid ${tokens.colorNeutralStroke2}`, gap: '1px',
        '&:hover': { backgroundColor: tokens.colorNeutralBackground3 },
    },
    detailListKey: { color: tokens.colorNeutralForeground3, fontWeight: '600', fontSize: '10px' },
    detailListValue: { color: tokens.colorNeutralForeground1, wordBreak: 'break-all' as const, whiteSpace: 'pre-wrap' as const },
    detailMonaco: { flex: 1, minHeight: 0 },
});
